url: "https://fcraighero.github.io"
title: "Francesco Craighero"
logo: assets/img/my_face.jpg

plugins:
- jekyll/scholar
- jekyll-seo-tag
- jekyll_picture_tag

include: ['_pages']

exclude:
  - mydoc_writers_*
  - bower_components
  - Gemfile
  - Rakefile
  - LICENSE
  - README.md

sass:
  sass_dir: _sass

scholar:
  style: apa
  locale: en
  bibliography_template: bib
  bibliography_class: "uk-list uk-list-large uk-list-bullet"
  sort_by: year
  order: descending