url: "fcraighero.github.io"
title: "Francesco Craighero"
logo: assets/img/my_face.jpg

plugins:
- jekyll/scholar
- jekyll-seo-tag

include: ['_pages']

sass:
  sass_dir: _sass

scholar:
  style: apa
  locale: en
  bibliography_template: bib
  bibliography_class: "uk-list uk-list-large uk-list-bullet"
  sort_by: year
  order: descending